backend:
  name: github
  repo: emenoghaebube21-eng/sovereignaqua-research-development-foundation
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:

  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Homepage"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }

      - file: "projects.html"
        label: "Projects"
        name: "projects"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }

      - file: "research.html"
        label: "Research"
        name: "research"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }

  - name: "media"
    label: "Press / Media"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
